server:
  port: 8081
spring:
  rabbitmq:
    host: 34.83.126.39
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        retry:
          initial-interval: 5000
          max-attempts: 3
queue:
  exchange: votacao-exchange
  route: votacao